# Generated by Django 4.2.4 on 2023-12-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/images/body')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(default=50000)),
                ('engineSize', models.IntegerField(default=2000)),
                ('drive', models.CharField(default='2WD', max_length=50)),
                ('price', models.IntegerField()),
                ('locationValue', models.CharField(max_length=2400)),
                ('yearOfManufacture', models.CharField(max_length=20)),
                ('isFeatured', models.BooleanField()),
                ('isAvailable', models.BooleanField()),
                ('transmission', models.CharField(max_length=50)),
                ('horsePower', models.IntegerField()),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuelType', models.CharField(max_length=50)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bodytype')),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/images/make')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.make')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/images/cars')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.make'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.model'),
        ),
    ]
